### PR TITLE
This change extends the api to support custom routing keys.

### PR DESCRIPTION
**Pull request by wolfeidau**
As the title mentions this simply adds some methods to enable configuring a custom routing key in the consume and produce methods. I have added methods to ensure the API remains compatible.

We are currently using the MQTT plugin which by default sends all messages to the `amq.topic` with a routing key matching the topic supplied by the client. For this reason we need different routing keys depending on the internal service the client is addressing.

An example of this is `$services/metrics/#' which as it's name implies carries messages destined for our metrics  service.

Hopefully this helps to understand the rationale for the change.

### CODE REVIEW

**Comment by armon** [comment]
@wolfeidau Looks good, but could you add a few tests? Thanks!

**Comment by armon** [comment]
@wolfeidau Just wanted to ping and see if you would have time to add tests for the changes. Thanks!

**Comment by wolfeidau** [comment]
Sorry thought this had been merged.

Will shoot through some tests.

**Comment by ryanuber** [comment]
These commits were brought in by #8, so they are now in master. We also pushed a pretty critical fix in 95c4460. I'm going to close this one out, thanks!

**Pull request closed without merging**
